### ISSUE TITLE
App crash because semi column Text string

### ISSUE THREAD

**Issue by Kirank212** [heiisenberrg/react-native-carousel-cards#17]
<img width="304" alt="image" src="https://user-images.githubusercontent.com/103688989/163469342-e378b708-8118-4d7e-a665-a19597856657.png">
              

please delete semi-column at the end of image component  

      <Image key={`index-images-${index}`} style={{ resizeMode: imageResizeMode, height: height, width: width }} source={item?.url.match(/http|https/g) ? { uri: item.url } : require(item.url)} />;

**Comment by heiisenberrg** [comment]
Fixed in v1.2.3
